### ISSUE TITLE
Using Refs as an Anchor

### ISSUE THREAD

**Issue by grinnsar** [davidrthorn/cross_reference#20]
Hi David!

FANTASTIC add-on - this saves me quite a bit of time, thanks for your hard work!

A question about anchoring - is it possible to double the Cross References feature as a shortcut (anchor) to skip to the Figure in the doc? Google docs has a "Bookmark" function that will accomplish this, but if I lace the bookmark into the same text as the Cross Ref (e.g., Figure 1), things get messy in hyperlink land.

Ideas?

Thank you!
Sarah

**Comment by davidrthorn** [comment]
Thanks Sarah.  So you have in mind that you could click on a reference and be taken to the matching label?

I don't think it's possible to replicate the bookmark functionality using the same mechanism. The issue is that Google Docs only allows navigation to anchors that have been added as bookmarks. Adding a link with a # does not create an anchor Docs can use.

Overcoming this would require building an anchor navigation system which, while possible, would be a significant undertaking. As a non-essential feature, I'm not sure it's worth it.

...but if anything comes to mind to make this work, I'll reconsider it. :)
