### ISSUE TITLE
Problem with updating (Update fails w/ and error message)

### ISSUE THREAD

**Issue by jonathanmwagstaff** [davidrthorn/cross_reference#64]
I am trying to update the cross references in my document but I keep getting an error

https://docs.google.com/document/d/1c4Rt-3Nu854qH-LVT5LLlbK6QoVSSB-tFeDLpelDw7Q/edit?usp=sharing

![Cross reference issue](https://user-images.githubusercontent.com/68005412/118177087-e51e4080-b43a-11eb-8f2a-e0557d46f376.png)

**Comment by davidrthorn** [comment]
Hi Jonathan

It looks like the problem is with the formatting of the equation labels on page 3.

First they are both on the same line, which is not supported at the moment. The add on assumes that each entity is labelled separately. Second, they are formatted inside some sort of box that's not a table (?). Finally, one of them is subscript.

I don't know what aspect of this formatting is causing the error, but I can remove it by placing a single label on the line below the equation in place of what's there.

I think you're choice of formatting might sadly have pushed the add on past its limit! Is it possible to do simple single-line labels for your equations?

**Comment by jonathanmwagstaff** [comment]
David Thorn

Thanks for telling me it is a formatting issue. I was just trying out your
program to see if it works. (I wanted to make sure it wouldn't be too buggy
to use.)

Thanks for responding so quickly.

Now I know what caused it so I can avoid it when writing.

Thanks again,

Jonathan

**Comment by jonathanmwagstaff** [comment]
I discovered that I didn't put the reference link inside the equation box.
The update does it. I had formatted the line originally to have the
equation box in the center and the link justified to the right (on the same
line as the equation box)
